// src/app/app/pages/flashcards/card-collections/card-collections.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { ButtonModule } from 'primeng/button';
import { MessageModule } from 'primeng/message';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { BreadcrumbService } from '../../../../core/services/breadcrumb.service';
import { PageTitleService } from '../../../../core/services/page-title.service';
import { CardCollectionsService } from '../../../services/card-collections.service';
import { CardCollectionCardComponent } from '../../../components/card-collection-card/card-collection-card.component';
import { CreateCardCollectionFormComponent } from '../../../components/create-card-collection-form/create-card-collection-form.component';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { OnPageChangeResponse, PaginationComponent } from '../../../../shared/components/pagination/pagination.component';
import { SearchService } from '../../../../core/services/search.service';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-card-collections',
  imports: [
    CommonModule,
    ButtonModule,
    MessageModule,
    ConfirmDialogModule,
    CreateCardCollectionFormComponent,
    CardCollectionCardComponent,
    LoadingSpinnerComponent,
    PaginationComponent
  ],
  templateUrl: './card-collections.component.html',
  styleUrl: './card-collections.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardCollectionsComponent implements OnInit {
  private service = inject(CardCollectionsService);
  private titleService = inject(PageTitleService);
  private breadcrumbService = inject(BreadcrumbService);
  private searchService = inject(SearchService);

  collections = this.service.collections;
  metadata = this.service.metadata;
  loading = this.service.loading;
  error = this.service.error;

  page = signal(1);
  pageSize = signal(10);
  dialogOpen = signal(false);

  ngOnInit() {
    this.titleService.setTitle('Card collections');
    this.breadcrumbService.set([{ label: 'Collections', path: '/app/card-collections' }]);
    this.service.fetch();
    this.searchService.search$.subscribe(async (search) => {
      this.service.fetch(search, this.page(), this.pageSize());
    })
  }

  openDialog() {
    this.dialogOpen.set(true);
  }

  closeDialog(refresh: boolean) {
    this.dialogOpen.set(false);
    if (refresh) this.reload();
  }

  async reload({ page, pageSize }: OnPageChangeResponse = { page: this.page(), pageSize: this.pageSize() }) {
    const search = await firstValueFrom(this.searchService.search$);
    this.service.fetch(search, page, pageSize);
  }
}

<section id="catalogs" class="flex flex-col h-full">
  <div class="flex justify-end items-center mb-5">
    <button pButton size="small" icon="ph ph-plus" label="New" (click)="openDialog()"></button>
  </div>

  @if (!loading() && !error() && collections().length) {
  <div class="flex flex-col justify-between h-full">
    <div class="grid grid-cols-4 gap-2 mb-5">
      @for (collection of collections(); track collection.id) {
      <app-card-collection-card [collection]="collection" (deleted)="reload()" />
      }
    </div>
    <app-pagination [metadata]="metadata()!" [page]="page()" [pageSize]="pageSize()" (onPageChange)="reload($event)" />
  </div>
  }

  @if (loading()) {
  <div class="flex flex-col justify-center items-center h-full">
    <app-loading-spinner />
  </div>
  }

  @if (error()) {
  <div class="flex flex-col justify-center items-center h-full">
    <p-message severity="error" [text]="error()!"></p-message>
  </div>
  }

  @if (!loading() && !error() && collections().length === 0) {
  <div class="flex flex-col justify-center items-center h-full">
    <i class="ph ph-empty" style="font-size: 32px"></i>
    <span class="font-semibold">No collections found.</span>
    <span>Start by creating a <span class="text-yellow-300">New</span> one</span>
  </div>
  }
</section>

<app-create-card-collection-form [visible]="dialogOpen()" (closed)="closeDialog($event)" (created)="reload()" />
<p-confirmDialog></p-confirmDialog>

// src/app/flashcards/pages/CardCollections.tsx
import { Button } from "primereact/button";
import { useEffect, useState } from "react";
import { usePageTitle } from "../../../shared/hooks/usePageTitle";
import { useCardCollections } from "../hooks/useCardCollections";
import { useAppBreadcrumb } from "../../../shared/hooks/useAppBreadcrumb";
import { CreateCardCollectionForm } from "../components/CreateCollectionForm";
import { LoadingSpinner } from "../../../shared/components/LoadingSpinner";
import { CardCollectionCard } from "../components/CardCollectionCard";
import { ConfirmDialog } from "primereact/confirmdialog";
import { Pagination } from "../../../shared/components/Pagination";
import { usePageParam } from "../../../shared/hooks/usePageParam";
import { usePageSizeParam } from "../../../shared/hooks/usePageSizeParam";
import { useSearchParam } from "../../../shared/hooks/useSearchParam";
import { Message } from "primereact/message";

export function CardCollections() {
  const { setPageTitle } = usePageTitle();
  const { setBreadcrumb } = useAppBreadcrumb();

  useEffect(() => {
    setPageTitle("Card collections");
    setBreadcrumb([{ label: "Collections", path: "/app/card-collections" }]);
  }, [setBreadcrumb, setPageTitle]);

  const [isCreateCollectionDialogOpen, setIsCreateCollectionDialogOpen] =
    useState(false);
  const page = usePageParam();
  const pageSize = usePageSizeParam();
  const search = useSearchParam();

  const collectionsQuery = useCardCollections(page, pageSize, search);
  const collections = collectionsQuery?.data?.data;
  const paginationMetadata = collectionsQuery?.data?.metadata;

  return (
    <>
      <section id="catalogs" className="flex flex-col h-full">
        <div className="flex justify-end items-center mb-5">
          <Button
            size="small"
            icon="ph ph-plus"
            label="New"
            onClick={() => setIsCreateCollectionDialogOpen(true)}
          />
        </div>

        {collections?.length && (
          <>
            <div className="grid grid-cols-4 gap-2 mb-5">
              {collections?.map((collection) => (
                <CardCollectionCard
                  collection={collection}
                  collectionsQuery={collectionsQuery}
                />
              ))}
            </div>
            <Pagination paginationMetadata={paginationMetadata!} />
          </>
        )}

        {collectionsQuery.isLoading && (
          <div className="flex flex-col justify-center items-center h-full">
            <LoadingSpinner />
          </div>
        )}
        {collectionsQuery.error && (
          <div className="flex flex-col justify-center items-center h-full">
            <Message severity="error" text={collectionsQuery.error.message} />
          </div>
        )}

        {collections?.length === 0 && (
          <div className="flex flex-col justify-center items-center h-full">
            <i className="ph ph-empty" style={{ fontSize: 32 }}></i>
            <span className="font-semibold">No collections found.</span>
            <span>
              Start by creating a <span className="text-yellow-300">New</span>{" "}
              one
            </span>
          </div>
        )}
      </section>
      <CreateCardCollectionForm
        isCreateCollectionDialogOpen={isCreateCollectionDialogOpen}
        setIsCreateCollectionDialogOpen={setIsCreateCollectionDialogOpen}
        collectionsQuery={collectionsQuery}
      />
      <ConfirmDialog />
    </>
  );
}
