// henshi-web/src/app/app/pages/flashcards/flashcards/flashcards.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { ConfirmationService, MessageService } from 'primeng/api';
import { ButtonModule } from 'primeng/button';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { TagModule } from 'primeng/tag';
import { ScrollPanelModule } from 'primeng/scrollpanel';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { PaginationComponent } from '../../../../shared/components/pagination/pagination.component';
import { CreateFlashcardFormComponent } from '../../../components/create-flashcard-form/create-flashcard-form.component';
import { FlashcardsService } from '../../../services/flashcards.service';

@Component({
  selector: 'app-flashcards',
  imports: [
    CommonModule,
    RouterModule,
    ButtonModule,
    ConfirmDialogModule,
    TagModule,
    ScrollPanelModule,
    PaginationComponent,
    LoadingSpinnerComponent,
    CreateFlashcardFormComponent,
  ],
  providers: [ConfirmationService, MessageService],
  templateUrl: './flashcards.component.html',
  styleUrl: './flashcards.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FlashcardsComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private confirmation = inject(ConfirmationService);
  private toast = inject(MessageService);
  protected flashcardsService = inject(FlashcardsService);

  collectionId = this.route.snapshot.paramMap.get('collectionId') ?? '';
  showCreateDialog = signal(false);
  isCreateDialogOpen = signal(false);

  flashcards = this.flashcardsService.flashcards;
  metadata = this.flashcardsService.metadata;
  loading = this.flashcardsService.loading;
  error = this.flashcardsService.error;

  ngOnInit() {
    if (this.collectionId) {
      this.flashcardsService.load(this.collectionId);
    }
  }

  confirmDelete(id: string) {
    this.confirmation.confirm({
      header: 'Do you really want to delete this flashcard?',
      message: 'This action is irreversible',
      icon: 'ph ph-warning',
      rejectLabel: 'Cancel',
      rejectButtonProps: {
        label: 'Cancel',
        severity: 'secondary',
        outlined: true,
      },
      acceptButtonProps: {
        label: 'Delete',
        severity: 'danger',
      },
      accept: () => {
        this.flashcardsService.delete(this.collectionId, id).subscribe({
          next: () => {
            this.toast.add({ severity: 'success', summary: 'Deleted', detail: 'Flashcard deleted successfully' });
            this.flashcardsService.load(this.collectionId);
          },
          error: () => {
            this.toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to delete flashcard' });
          },
        });
      },
    });
  }
}

<div class="flex justify-end items-center mb-5">
    <div class="flex gap-2">
        <a [routerLink]="['recall']">
            <p-button icon="ph ph-play" size="small" label="Recall"></p-button>
        </a>
        <p-button size="small" icon="ph ph-plus" label="New" (onClick)="isCreateDialogOpen.set(true)">
        </p-button>
    </div>
</div>

<ng-container *ngIf="loading(); else loaded">
    <app-loading-spinner></app-loading-spinner>
</ng-container>

<ng-template #loaded>
    <ng-container *ngIf="!error() && flashcards().length > 0; else empty">
        <p-scrollPanel styleClass="h-4/5">
            <div *ngFor="let flashcard of flashcards(); let i = index" class="bg-slate-700 p-3 rounded-lg mb-3">
                <div class="flex justify-between">
                    <div class="flex gap-2">
                        <span class="bg-slate-500 py-2 px-4 rounded-lg text-lg font-semibold">
                            {{ i + 1 }}
                        </span>
                        <p-tag severity="info" [value]="flashcard.grade"></p-tag>
                    </div>
                    <div class="flex gap-2">
                        <p-button size="small" icon="ph ph-trash" severity="secondary"
                            (onClick)="confirmDelete(flashcard.id)">
                        </p-button>
                    </div>
                </div>
                <div class="grid grid-cols-2 gap-2 mt-3 overflow-auto overflow-x-hidden">
                    <p-scrollPanel styleClass="bg-slate-800 p-2 rounded-lg h-48">
                        {{ flashcard.question }}
                    </p-scrollPanel>
                    <p-scrollPanel styleClass="bg-slate-800 p-2 rounded-lg h-48">
                        {{ flashcard.answer }}
                    </p-scrollPanel>
                </div>
            </div>
        </p-scrollPanel>
        <app-pagination [metadata]="metadata()!" [pageSize]="5">
        </app-pagination>
    </ng-container>

    <ng-template #empty>
        <div class="flex flex-col justify-center items-center h-3/4">
            <i class="pi pi-info-circle" style="font-size: 32px"></i>
            <span class="font-semibold">No flashcards found.</span>
            <span>
                Start by creating a <span class="text-yellow-300">New</span> one
            </span>
        </div>
    </ng-template>
</ng-template>

<app-create-flashcard-form [visible]="isCreateDialogOpen()" (closed)="isCreateDialogOpen.set(false)"
    [collectionId]="collectionId" (created)="flashcardsService.load(collectionId)">
</app-create-flashcard-form>

<p-confirmDialog></p-confirmDialog>

// src/app/flashcards/pages/Flashcards.tsx
import { useEffect, useState } from "react";
import { NavLink, useLocation, useParams } from "react-router-dom";
import { useAppBreadcrumb } from "../../../shared/hooks/useAppBreadcrumb";
import { Button } from "primereact/button";
import { CreateFlashcardForm } from "../components/CreateFlashcardForm";
import { useFlashcards } from "../hooks/useFlashcards";
import { LoadingSpinner } from "../../../shared/components/LoadingSpinner";
import { Tag } from "primereact/tag";
import { useDeleteFlashcard } from "../hooks/useDeleteFlashcard";
import { confirmDialog, ConfirmDialog } from "primereact/confirmdialog";
import { useToast } from "../../../shared/hooks/useToast";
import { ScrollPanel } from "primereact/scrollpanel";
import { getGradeLabel } from "../types/Flashcard";
import { usePageParam } from "../../../shared/hooks/usePageParam";
import { usePageSizeParam } from "../../../shared/hooks/usePageSizeParam";
import { useSearchParam } from "../../../shared/hooks/useSearchParam";
import { Pagination } from "../../../shared/components/Pagination";

export function Flashcards() {
  const params = useParams();
  const collectionId = params.collectionId ?? "";

  const { setBreadcrumb } = useAppBreadcrumb();
  const currentLocation = useLocation();
  const { showSuccessToast, showErrorToast } = useToast();

  useEffect(() => {
    setBreadcrumb([
      { label: "Collections", path: "/app/card-collections" },
      { label: "Flashcards", path: currentLocation.pathname },
    ]);
  }, [currentLocation.pathname, setBreadcrumb]);

  const page = usePageParam();
  const pageSize = usePageSizeParam(5);
  const search = useSearchParam();

  const flashcardsQuery = useFlashcards(collectionId, page, pageSize, search);
  const [isCreateFlashcardDialogOpen, setIsCreateFlashcardDialogOpen] =
    useState(false);

  const deleteFlashcardMutation = useDeleteFlashcard();

  if (!collectionId) return <>Invalid collection</>;

  const flashcards = flashcardsQuery.data?.data;
  const paginationMetadata = flashcardsQuery.data?.metadata;

  function onDeleteFlashcardClick(id: string) {
    confirmDialog({
      header: `Do you really want to delete this flashcard?`,
      message: "This action is irreversible",
      icon: "ph ph-warning",
      acceptClassName: "p-button-danger",
      modal: true,
      draggable: false,
      resizable: false,
      accept: () => {
        deleteFlashcardMutation.mutate(
          { collectionId, id },
          {
            onSuccess: async () => {
              showSuccessToast("Flashcard deleted successfully");
              await flashcardsQuery.refetch();
            },
            onError: (e) => {
              showErrorToast(
                "Error while trying to delete flashcard",
                e.message
              );
            },
          }
        );
      },
    });
  }

  return (
    <>
      <div className="flex justify-end items-center mb-5">
        <div className="flex gap-2">
          <NavLink to={currentLocation.pathname + "/recall"}>
            <Button icon="ph ph-play" size="small" label="Recall" />
          </NavLink>
          <Button
            size="small"
            icon="ph ph-plus"
            label="New"
            onClick={() => setIsCreateFlashcardDialogOpen(true)}
          />
        </div>
      </div>
      {flashcards && flashcards.length > 0 && (
        <>
          <ScrollPanel className="h-4/5">
            {flashcards?.map((flashcard, i) => (
              <div
                key={flashcard.id}
                className="bg-slate-700 p-3 rounded-lg mb-3"
              >
                <div className="flex justify-between">
                  <div className="flex gap-2">
                    <span className="bg-slate-500 py-2 px-4 rounded-lg text-lg font-semibold">
                      {i + 1}
                    </span>
                    <Tag severity="info" value={getGradeLabel(flashcard.grade)} />
                  </div>
                  <div className="flex gap-2">
                    <Button
                      size="small"
                      icon="ph ph-trash"
                      severity="secondary"
                      tooltip="Delete"
                      tooltipOptions={{ position: "top" }}
                      onClick={() => onDeleteFlashcardClick(flashcard.id)}
                    />
                  </div>
                </div>
                <div
                  key={flashcard.id}
                  className="grid grid-cols-2 gap-2 mt-3 overflow-auto overflow-x-hidden"
                >
                  <ScrollPanel className="bg-slate-800 p-2 rounded-lg h-48">
                    {flashcard.question}
                  </ScrollPanel>
                  <ScrollPanel className="bg-slate-800 p-2 rounded-lg h-48">
                    {flashcard.answer}
                  </ScrollPanel>
                </div>
              </div>
            ))}
          </ScrollPanel>
          <Pagination
            paginationMetadata={paginationMetadata!}
            defaultPageSize={5}
            rowsPerPageOptions={[5, 10, 15]}
          />
        </>
      )}
      {flashcardsQuery.isLoading && (
        <div className="flex flex-col justify-center items-center h-3/4">
          <LoadingSpinner />
        </div>
      )}
      {(flashcards?.length === 0 || flashcardsQuery.error) && (
        <div className="flex flex-col justify-center items-center h-3/4">
          <i className="ph ph-empty" style={{ fontSize: 32 }}></i>
          <span className="font-semibold">No flashcards found.</span>
          <span>
            Start by creating a <span className="text-yellow-300">New</span> one
          </span>
        </div>
      )}
      <CreateFlashcardForm
        isCreateFlashcardDialogOpen={isCreateFlashcardDialogOpen}
        setIsCreateFlashcardDialogOpen={setIsCreateFlashcardDialogOpen}
        collectionId={collectionId}
        flashcardsQuery={flashcardsQuery}
      />
      <ConfirmDialog />
    </>
  );
}
