// src/app/flashcards/components/CardCollectionCard.tsx
import { UseQueryResult } from "@tanstack/react-query";
import { Button } from "primereact/button";
import { Menu } from "primereact/menu";
import { MenuItem } from "primereact/menuitem";
import { useRef, useState, SyntheticEvent } from "react";
import { NavLink } from "react-router-dom";
import { ListCardCollectionsResponse } from "../hooks/useCardCollections";
import { ROUTES } from "../../../shared/consts/routes";
import { useToast } from "../../../shared/hooks/useToast";
import { useDeleteCardCollection } from "../hooks/useDeleteCardCollection";
import { CardCollection } from "../types/CardCollection";
import { confirmDialog } from "primereact/confirmdialog";

type CollectionCardProps = {
  collection: CardCollection;
  collectionsQuery: UseQueryResult<ListCardCollectionsResponse, Error>;
};

export function CardCollectionCard({
  collection,
  collectionsQuery,
}: CollectionCardProps) {
  const deleteCardCollectionMutation = useDeleteCardCollection();
  const { showSuccessToast, showErrorToast } = useToast();

  const cardMenu = useRef<Menu>(null);
  const [currentSelectedCollectionId, setCurrentSelectedCollectionId] =
    useState<string>();
  const cardMenuItems: MenuItem[] = [
    {
      label: "Delete",
      icon: "ph ph-trash",
      command: async function () {
        confirmDialog({
          header: `Do you really want to delete "${collection.title}"?`,
          message:
            "This action is irreversible and will delete all the flashcards assigned to it.",
          icon: "ph ph-warning",
          acceptClassName: "p-button-danger",
          modal: true,
          draggable: false,
          resizable: false,
          accept: () => {
            if (currentSelectedCollectionId) {
              deleteCardCollectionMutation.mutate(currentSelectedCollectionId, {
                onSuccess: async () => {
                  showSuccessToast("Collection deleted successfully");
                  await collectionsQuery.refetch();
                },
                onError: (e) => {
                  showErrorToast(
                    "Error while trying to delete collection",
                    e.message
                  );
                },
              });
            }
          },
        });
      },
    },
  ];

  function onCollectionOptionsButtonClick(
    e: SyntheticEvent,
    collectionId: string
  ) {
    e.preventDefault();
    setCurrentSelectedCollectionId(collectionId);
    cardMenu.current?.toggle(e);
  }

  return (
    <NavLink
      to={`${ROUTES.cardCollections}/${collection.id}/flashcards`}
      onClick={(e) =>
        deleteCardCollectionMutation.isPending && e.preventDefault()
      }
      className="flex flex-col min-h-38 bg-slate-800 border-1 border-slate-600 hover:bg-slate-700 disabled transition rounded-lg p-2 cursor-pointer"
    >
      <div className="flex justify-between mt-1">
        <div className="flex items-center">
          <div className="flex items-center bg-slate-600 rounded-lg p-2 me-2">
            <i className={"ph " + collection.icon}></i>
          </div>
          <span className="font-semibold text-lg">{collection.title}</span>
        </div>
        <div>
          <Button
            onClick={(e) => onCollectionOptionsButtonClick(e, collection.id)}
            severity="secondary"
            disabled={deleteCardCollectionMutation.isPending}
            text
            icon="ph ph-dots-three-vertical"
          />
          <Menu popup ref={cardMenu} model={cardMenuItems}></Menu>
        </div>
      </div>
      <span className="my-2">
        {collection.description ?? (
          <span className="text-slate-400">No description</span>
        )}
      </span>
    </NavLink>
  );
}

// henshi-web/src/app/app/components/card-collection-card/card-collection-card.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, EventEmitter, inject, Input, Output } from '@angular/core';
import { RouterModule } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { MenuModule } from 'primeng/menu';
import { ToastService } from '../../../core/services/toast.service';
import { CardCollectionsService } from '../../services/card-collections.service';
import { CardCollection } from '../../../core/types/CardCollection';
import { ConfirmDialog, ConfirmDialogModule } from "primeng/confirmdialog";
import { ConfirmationService } from 'primeng/api';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-card-collection-card',
  imports: [CommonModule, RouterModule, ButtonModule, MenuModule, ConfirmDialogModule, ConfirmDialog],
  templateUrl: './card-collection-card.component.html',
  styleUrl: './card-collection-card.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardCollectionCardComponent {
  @Input() collection!: CardCollection;
  @Output() deleted = new EventEmitter<void>();

  private service = inject(CardCollectionsService);
  private toast = inject(ToastService);
  private confirmation = inject(ConfirmationService);

  confirmDelete(event: Event) {
    this.confirmation.confirm(
      {
        target: event.target as EventTarget,
        header: 'Do you really want to delete this collection?',
        message: 'This action is irreversible and will delete all flashcards associated with it',
        icon: 'ph ph-warning',
        rejectLabel: 'Cancel',
        rejectButtonProps: {
          label: 'Cancel',
          severity: 'secondary',
          outlined: true,
        },
        acceptButtonProps: {
          label: 'Delete',
          severity: 'danger',
        },
        accept: () => {
          this.service.delete(this.collection.id).subscribe({
            next: () => {
              this.toast.success('Collection deleted successfully');
              this.deleted.emit();
            },
            error: (err: HttpErrorResponse) => {
              this.toast.error('Error while trying to delete collection', err.message);
            }
          })
        },
        reject: () => { },
      }
    );
    event.preventDefault();
  }
}

<p-confirm-dialog></p-confirm-dialog>

<a
    [routerLink]="['/app/card-collections', collection.id, 'flashcards']"
    class="flex flex-col min-h-38 bg-slate-800 border border-slate-600
            hover:bg-slate-700 transition rounded-lg p-2 cursor-pointer"
>
    <div class="flex justify-between mt-1">
    <div class="flex items-center">
        <div class="flex items-center bg-slate-600 rounded-lg p-2 me-2">
        <i class="ph {{ collection.icon }}"></i>
        </div>
        <span class="font-semibold text-lg">{{ collection.title }}</span>
    </div>
    <div>
        <button
        pButton
        severity="secondary"
        text
        icon="ph ph-dots-three-vertical"
        (click)="confirmDelete($event)"
        ></button>
    </div>
    </div>
    <span class="my-2">
        {{ collection.description || 'No description' }}
    </span>
</a>
