// src/shared/layouts/AppLayout.tsx
import { Outlet } from "react-router-dom";
import AppSidebar from "../components/AppSidebar";
import { AppBreadcrumb } from "../components/AppBreadcrumb";
import { AppTopbar } from "../components/AppTopbar";

export const AppLayout = () => {
  return (
    <div className="flex bg-slate-950">
      <AppSidebar />
      <div className="flex flex-col w-full h-screen">
        <AppTopbar />
        <div className="p-5 m-2 rounded-lg bg-slate-900 border-slate-700 border-1 shadow-lg h-11/12">
          <AppBreadcrumb />
          <Outlet />
        </div>
      </div>
    </div>
  );
};

// henshi-web/src/app/app/layouts/app/app-layout/app-layout.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from "@angular/router";
import { AppSidebarComponent } from '../../../components/app-sidebar/app-sidebar.component';
import { AppTopbarComponent } from '../../../components/app-topbar/app-topbar.component';
import { AppBreadcrumbComponent } from '../../../components/app-breadcrumb/app-breadcrumb.component';

@Component({
  selector: 'app-app-layout',
  imports: [RouterOutlet, AppSidebarComponent, AppTopbarComponent, AppBreadcrumbComponent],
  templateUrl: './app-layout.component.html',
  styleUrl: './app-layout.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppLayoutComponent { }

<div class="flex bg-slate-950">
  <app-app-sidebar></app-app-sidebar>

  <div class="flex flex-col w-full h-screen">
    <app-app-topbar></app-app-topbar>

    <div class="p-5 m-2 rounded-lg bg-slate-900 border-slate-700 border-1 shadow-lg h-11/12">
      <app-app-breadcrumb></app-app-breadcrumb>
      <router-outlet></router-outlet>
    </div>
  </div>
</div>
