// henshi-web/src/app/app/components/app-breadcrumb/app-breadcrumb.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BreadcrumbModule } from 'primeng/breadcrumb';
import { MenuItem } from 'primeng/api';
import { BreadcrumbService } from '../../../core/services/breadcrumb.service';

@Component({
  selector: 'app-app-breadcrumb',
  imports: [CommonModule, BreadcrumbModule],
  templateUrl: './app-breadcrumb.component.html',
  styleUrl: './app-breadcrumb.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppBreadcrumbComponent {
  private bc = inject(BreadcrumbService);

  items: MenuItem[] = [];
  home: MenuItem = { icon: 'ph ph-house', routerLink: '/' };

  constructor() {
    this.bc.crumbs$.subscribe((crumbs) => {
      this.items = crumbs.map((b, i) => ({
        label: b.label,
        template: () => {
          const isLast = i === crumbs.length - 1;
          return `<a class="${isLast ? 'text-cyan-400' : ''}" href="${b.path}">${b.label}</a>`;
        },
        routerLink: b.path,
      }));
    });
  }
}

@if (items.length > 0) {
<p-breadcrumb class="mb-5" [model]="items" [home]="home" [style]="{
        backgroundColor: 'transparent'
      }"></p-breadcrumb>
}

// src/shared/components/AppBreadcrumb.tsx
import { BreadCrumb } from "primereact/breadcrumb";
import { useAppBreadcrumb } from "../hooks/useAppBreadcrumb";
import { MenuItem } from "primereact/menuitem";
import { NavLink } from "react-router-dom";

export function AppBreadcrumb() {
    const { breadcrumb } = useAppBreadcrumb()

    const items: MenuItem[] = breadcrumb.map((b, i) => ({ label: b.label, template: () => <NavLink className={i === breadcrumb.length - 1 ? "text-cyan-400" : ""} to={b.path}>{b.label}</NavLink> }))

    return <>{breadcrumb.length > 0 && <BreadCrumb className="mb-5" model={items} home={{ icon: 'ph ph-house', url: '/' }} pt={{ root: { style: { backgroundColor: 'transparent', border: 0, padding: 0 } } }}></BreadCrumb>}</>
}
