// src/app/app/components/app-topbar/app-topbar.component.ts
import { ChangeDetectionStrategy, Component, effect, inject, OnDestroy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged, Subscription } from 'rxjs';
import { Router } from '@angular/router';

import { AvatarModule } from 'primeng/avatar';
import { MenuModule } from 'primeng/menu';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';
import { RippleModule } from 'primeng/ripple';
import { MenuItem } from 'primeng/api';
import { AuthenticationService } from '../../../auth/services/auth.service';
import { PageTitleService } from '../../../core/services/page-title.service';
import { User } from '@auth0/auth0-angular';
import { SearchService } from '../../../core/services/search.service';

@Component({
  selector: 'app-app-topbar',
  imports: [
    CommonModule,
    ReactiveFormsModule,
    AvatarModule,
    MenuModule,
    ButtonModule,
    InputTextModule,
    IconFieldModule,
    InputIconModule,
    RippleModule
  ],
  templateUrl: './app-topbar.component.html',
  styleUrl: './app-topbar.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppTopbarComponent {
  private router = inject(Router);
  private pageTitle = inject(PageTitleService);
  private auth = inject(AuthenticationService);
  private searchService = inject(SearchService);

  title = signal<string>('');
  user = signal<User | null | undefined>(null);

  searchCtrl = new FormControl<string>('', { nonNullable: true });
  subs = new Subscription();

  items: MenuItem[] = [
    {
      label: 'Logout',
      icon: 'ph ph-arrow-square-left',
      command: () => this.auth.logout(),
    },
  ];

  constructor() {
    this.subs.add(this.pageTitle.title$.subscribe(t => this.title.set(t)));

    this.subs.add(this.auth.user$.subscribe(u => (this.user.set(u))));

    this.subs.add(
      this.searchCtrl.valueChanges
        .pipe(debounceTime(400), distinctUntilChanged())
        .subscribe((search) => {
          this.searchService.setSearch((search ?? '').trim());
        }),
    );
  }

  ngOnDestroy() {
    this.subs.unsubscribe();
  }
}

<div class="flex justify-between items-center me-3">
    <span class="font-semibold text-2xl mt-3 mb-2 ps-2">{{ title() }}</span>

    <div class="flex gap-3 items-center">
        <p-iconField class="mt-2" iconPosition="left">
            <p-inputIcon class="ph ph-magnifying-glass" [style.top.px]="14"></p-inputIcon>
            <input type="text" pInputText class="p-inputtext-sm" [formControl]="searchCtrl" placeholder="Search" />
        </p-iconField>

        <i class="ph ph-bell p-overlay-badge mt-2 hover:bg-slate-700 rounded-full p-2" style="font-size: 1.5rem"></i>

        <p-menu #userMenu [popup]="true" [model]="items"></p-menu>

        <div (click)="userMenu.toggle($event)"
            class="flex items-center hover:bg-slate-700 p-1 mt-2 rounded-lg cursor-pointer">
            @if (user()?.picture) {
                <p-avatar [image]="user()?.picture!" size="normal"
                    shape="circle"></p-avatar>
            }

            @if (user()?.given_name) {
                <span class="ms-3 font-semibold">{{ user()?.given_name }}</span>
            }
            
            <i class="ph ph-caret-down ms-2"></i>
        </div>
    </div>
</div>

// src/shared/components/AppTopbar.tsx
import { Avatar } from "primereact/avatar";
import { usePageTitle } from "../hooks/usePageTitle";
import { useAuth } from "../hooks/useAuth";
import { ChangeEvent, useEffect, useRef } from "react";
import { Menu } from "primereact/menu";
import { MenuItem } from "primereact/menuitem";
import { Button } from "primereact/button";
import { InputText } from "primereact/inputtext";
import { IconField } from "primereact/iconfield";
import { InputIcon } from "primereact/inputicon";
import { useSearchParams } from "react-router-dom";
import { useDebounce } from "primereact/hooks";

export function AppTopbar() {
  const { pageTitle } = usePageTitle();
  const { user, logout } = useAuth();
  const [, setSearchParams] = useSearchParams();
  const [, debouncedValue, setInputValue] = useDebounce("", 400);

  const userProfilePicture = user?.picture;
  const userFirstNameLetter = user?.given_name?.[0];

  const menu = useRef<Menu>(null);
  const items: MenuItem[] = [
    {
      template: () => (
        <Button
          onClick={logout}
          className="w-full"
          label="Logout"
          icon="ph ph-arrow-square-left"
          severity="secondary"
          text
        />
      ),
    },
  ];

  function onSearch(event: ChangeEvent<HTMLInputElement>) {
    const search = event.target.value.trim();
    setInputValue(search);
  }

  useEffect(() => {
    const search = debouncedValue;
    if (search) {
      setSearchParams((params) => ({
        ...Object.fromEntries(params.entries()),
        page: "1",
        search: debouncedValue,
      }));
    } else {
      setSearchParams((params) => {
        params.delete("search");
        return {
          ...Object.fromEntries(params.entries()),
        };
      });
    }
  }, [debouncedValue, setSearchParams]);

  return (
    <div className="flex justify-between items-center me-3">
      <span className="font-semibold text-2xl mt-3 mb-2 ps-2">{pageTitle}</span>
      <div className="flex gap-3 items-center">
        <IconField className="mt-2" iconPosition="left">
          <InputIcon
            className="ph ph-magnifying-glass"
            style={{ top: "0.9em" }}
          ></InputIcon>
          <InputText
            className="p-inputtext-sm"
            placeholder="Search"
            onChange={onSearch}
          />
        </IconField>
        <i
          className="ph ph-bell p-overlay-badge mt-2 hover:bg-slate-700 rounded-full p-2"
          style={{ fontSize: "1.5rem" }}
        >
          {/* <Badge value="0"></Badge> */}
        </i>
        <div
          onClick={(e) => menu.current?.toggle(e)}
          className="flex items-center hover:bg-slate-700 p-1 mt-2 rounded-lg cursor-pointer"
        >
          {userProfilePicture ? (
            <Avatar image={userProfilePicture} size="large" shape="circle" />
          ) : (
            <Avatar
              label={userFirstNameLetter}
              size="large"
              style={{ backgroundColor: "#F5CB5C", color: "#18181B" }}
              shape="circle"
            ></Avatar>
          )}
          <span className="ms-3 font-semibold">{user?.given_name}</span>
          <i className="ph ph-caret-down ms-2"></i>
        </div>
      </div>

      <Menu
        model={items}
        popup
        ref={menu}
        id="popup_menu_right"
        popupAlignment="right"
      />
    </div>
  );
}
