// src/app/app/components/recall-card/recall-card.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-recall-card',
  imports: [LoadingSpinnerComponent, CommonModule],
  templateUrl: './recall-card.component.html',
  styleUrl: './recall-card.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RecallCardComponent { 
  @Input() text = '';
  @Input() side: 'FRONT' | 'BACK' = 'FRONT';
  @Input() isLoading = false;
}

@if (isLoading) {
<app-loading-spinner></app-loading-spinner>
} @else {
<div class='absolute inset-0 h-full w-full p-3 bg-slate-800 border-1 border-slate-700 rounded-xl text-center overflow-y-scroll [backface-visibility:hidden]'
    [ngClass]="{ 
        '[transform:rotateY(180deg)]': side === 'BACK', 
        'flex justify-center items-center': isLoading 
    }">
    {{ text }}
</div>
}

// src/app/flashcards/components/RecallCard.tsx
import { LoadingSpinner } from "../../../shared/components/LoadingSpinner";

type RecallCardProps = {
  text: string;
  side: "FRONT" | "BACK";
  isLoading: boolean;
};

export function RecallCard({ text, side, isLoading }: RecallCardProps) {
  return (
    <div
      className={
        (side === "BACK" ? "[transform:rotateY(180deg)] " : "") +
        (isLoading ? "flex justify-center items-center " : "") +
        "absolute inset-0 h-full w-full p-3 bg-slate-800 border-1 border-slate-700 rounded-xl text-center [backface-visibility:hidden] overflow-y-scroll"
      }
    >
      {isLoading ? <LoadingSpinner /> : text}
    </div>
  );
}
